/**
 * AdornableMixin — host of a `fixtures` collection, parallel to
 * ExitableMixin's `exits` map.
 *
 * A Container with this mixin gains a separate, non-portable
 * population of Stuff attached *to* it: wall sconces, ceiling lamps,
 * the per-side `BoundaryAnchor` of a Boundary. Fixtures are NOT in
 * `getContents()`; they are surfaced separately via `getFixtures()`
 * and (for channel-shaped consumers) the convenience getters
 * `getFixtureBoundaries()` / `getFixtureLightSources()`.
 *
 * Constraint: composed on `Stuff & Container`. Locations compose it
 * for free; every `CartesianLocation` / `SphericalLocation` ships
 * with `getFixtures()`.
 *
 * **Slotted underpinning (post-retrofit).** Adornable composes
 * `SlottedMixin` and overrides `getSlotNames` / `getSlotSpec` to
 * derive its slot universe from the live fixture map. Fixtures are
 * keyed by synthetic slot names (`fixture:1`, `fixture:2`, …)
 * generated by an instance-local counter. The substrate's
 * `canOccupy` requires occupants to compose `AdornmentMixin`; the
 * back-reference (`adornedTo`) stays as the parent pointer the slot
 * framework doesn't carry.
 *
 * Authors who want meaningful slot names pass an explicit
 * `slotName` to `addFixture(f, slotName)` — useful for content like
 * cars where authors want `seatbelt:driver` instead of `fixture:1`.
 *
 * Lifecycle: `onDestruct()` destructs every fixture before chaining
 * to super. The fixture's own `onDestruct()` is responsible for
 * unhooking from any Boundary it's an anchor of (see
 * `BoundaryAnchor.onDestruct`).
 *
 * Containment invariant: an `Adornment` whose `adornedTo` is non-null
 * cannot be moved into a Container's `contents` via
 * `ContainmentApi.move` — see the pre-flight veto in
 * `containment.ts`.
 */

import type { MixinConstructor, FieldMeta } from '../mixin';
import type { Stuff } from '../stuff/Stuff';
import type { Container } from '../spatial/Container';
import type { Adornment } from './Adornment';
import type { Slottable } from '../slot/Slottable';
import type { Slotted, SlotSpec } from '../slot/Slotted';
import { StuffApi } from '../../api/stuff';
import { MixinApi } from '../../api/mixin';
import { SlottedMixin } from '../slot/Slotted';

import type { Boundary } from './Boundary';
import { BoundaryAnchor } from './BoundaryAnchor';

/**
 * One `adornments` entry. A bare path string clones the template and
 * attaches it with the next synthetic slot name; the object form pins a
 * meaningful `slot` (the same names `addFixture` accepts — e.g.
 * `sign:left`). The referenced template MUST compose `AdornmentMixin`
 * (the applier guards and throws otherwise).
 *
 * Fixtures are per-instance by nature (two Veshko signs are two
 * objects), so the applier always **clones** — there is no singleton
 * dispatch like `applyPopulates`.
 */
export type AdornmentSpec = string | { template: string; slot?: string };

/** Public shape added by AdornableMixin. */
export interface Adornable {
  /**
   * Attach a fixture. If `slotName` is omitted, the fixture is keyed
   * with the next synthetic name (`fixture:1`, `fixture:2`, …) —
   * the counter is instance-local and runtime-only. Returns false if
   * the fixture is already attached.
   */
  addFixture(f: Stuff & Adornment, slotName?: string): boolean;
  removeFixture(f: Stuff & Adornment): boolean;
  hasFixture(f: Stuff & Adornment): boolean;
  getFixtures(): readonly (Stuff & Adornment)[];
  getFixtureBoundaries(): Boundary[];
  getFixtureLightSources(): (Stuff & Adornment)[];
  getFixtureSmellSources(): (Stuff & Adornment)[];
  getFixtureSoundSources(): (Stuff & Adornment)[];
  /**
   * @hook Invoked by the `Hydrator`'s Phase-2 instruction dispatch from
   *   a template's `adornments` field. **Instruction applier** — clones
   *   each spec's template and attaches it as a fixture via
   *   `addFixture`; the spec is not retained and there is no paired
   *   getter (the live fixtures are read via `getFixtures()`). Fixtures
   *   are runtime-only, so this re-runs and rebuilds them on every
   *   hydrate (the `BoundaryAnchor` reconstruction model).
   */
  applyAdornments(specs: AdornmentSpec[]): Promise<void>;
}

export function AdornableMixin<TBase extends MixinConstructor<Stuff & Container>>(
  Base: TBase
) {
  return class AdornableMixin extends SlottedMixin(Base) {
    static _mixinName = 'AdornableMixin';

    /**
     * Instruction field consumed by `applyAdornments`. The YAML data is
     * an array of `AdornmentSpec` entries; Phase 2 clones each and
     * attaches it as a fixture. The `applyExits` / `applyPopulates`
     * precedent — declarative content over the imperative `addFixture`.
     */
    static fieldMeta: FieldMeta = {
      adornments: { instruction: true, authorable: true },
    };

    /**
     * Phase 2 applier — clone each adornment template and attach it as a
     * fixture. Mirrors `applyPopulates`, minus the singleton dispatch:
     * fixtures are per-instance, so every entry is cloned fresh. A
     * template that doesn't compose `AdornmentMixin` is a configuration
     * error (it can't be a fixture) and throws, naming the path.
     */
    async applyAdornments(specs: AdornmentSpec[]): Promise<void> {
      if (!Array.isArray(specs)) return;
      for (const spec of specs) {
        const path = typeof spec === 'string' ? spec : spec?.template;
        if (typeof path !== 'string' || path.length === 0) continue;
        const slot = typeof spec === 'string' ? undefined : spec.slot;
        const inst = await StuffApi.clone<Stuff>(path);
        if (!MixinApi.isAdornment(inst)) {
          throw new Error(
            `AdornableMixin.applyAdornments: '${path}' is not an ` +
              `Adornment (it must compose AdornmentMixin to attach as a ` +
              `fixture)`
          );
        }
        this.addFixture(inst, slot);
      }
    }

    /**
     * Fixtures keyed by slot name. Single source of truth — the
     * Slotted base's `slots` Map stays empty for Adornable hosts
     * because `occupy` / `vacate` on Adornable are routed through
     * `addFixture` / `removeFixture`.
     *
     * Runtime-only — fixtures are reconstructed by seed clone hooks
     * (`BoundaryApi.attachExistingBoundary`).
     */
    protected fixtureSlots: Map<string, Stuff & Adornment> = new Map();

    /** Counter for synthetic slot names. Instance-local, runtime-only. */
    protected nextFixtureIndex: number = 1;

    addFixture(f: Stuff & Adornment, slotName?: string): boolean {
      // Already attached? No-op.
      for (const existing of this.fixtureSlots.values()) {
        if (existing === f) return false;
      }
      const name = slotName ?? `fixture:${this.nextFixtureIndex++}`;
      if (this.fixtureSlots.has(name)) {
        throw new Error(
          `Adornable.addFixture: slot '${name}' is already occupied`
        );
      }
      this.fixtureSlots.set(name, f);
      f.setAdornedTo(this as unknown as Stuff & Adornable);
      return true;
    }

    removeFixture(f: Stuff & Adornment): boolean {
      let foundKey: string | null = null;
      for (const [k, v] of this.fixtureSlots.entries()) {
        if (v === f) {
          foundKey = k;
          break;
        }
      }
      if (foundKey === null) return false;
      this.fixtureSlots.delete(foundKey);
      // Only clear the back-reference if it still points at us.
      if (f.getAdornedTo() === (this as unknown as Stuff & Adornable)) {
        f.setAdornedTo(null);
      }
      return true;
    }

    hasFixture(f: Stuff & Adornment): boolean {
      for (const existing of this.fixtureSlots.values()) {
        if (existing === f) return true;
      }
      return false;
    }

    getFixtures(): readonly (Stuff & Adornment)[] {
      return Array.from(this.fixtureSlots.values());
    }

    getFixtureBoundaries(): Boundary[] {
      const seen = new Set<string>();
      const out: Boundary[] = [];
      for (const f of this.fixtureSlots.values()) {
        if (!BoundaryAnchor.is(f)) continue;
        const boundary = f.getBoundary();
        if (!boundary) continue;
        const id = (boundary as unknown as Stuff).stuffId;
        if (seen.has(id)) continue;
        seen.add(id);
        out.push(boundary);
      }
      return out;
    }

    getFixtureLightSources(): (Stuff & Adornment)[] {
      const out: (Stuff & Adornment)[] = [];
      for (const f of this.fixtureSlots.values()) {
        if (isLightSourceMarker(f)) out.push(f);
      }
      return out;
    }

    getFixtureSmellSources(): (Stuff & Adornment)[] {
      const out: (Stuff & Adornment)[] = [];
      for (const f of this.fixtureSlots.values()) {
        if (isSmellSourceMarker(f)) out.push(f);
      }
      return out;
    }

    getFixtureSoundSources(): (Stuff & Adornment)[] {
      const out: (Stuff & Adornment)[] = [];
      for (const f of this.fixtureSlots.values()) {
        if (isSoundSourceMarker(f)) out.push(f);
      }
      return out;
    }

    /**
     * Slot universe (Pattern C from slot.md). Derives from
     * the live fixture keying.
     */
    getSlotNames(): readonly string[] {
      return Array.from(this.fixtureSlots.keys());
    }

    getSlotSpec(name: string): SlotSpec | null {
      if (!this.fixtureSlots.has(name)) return null;
      return { name, accepts: 'AdornmentMixin' };
    }

    /**
     * Slotted-side mutators — routed through addFixture/removeFixture
     * so the synthetic-name keying and back-reference stay
     * consistent. The Slotted base's own `slots` Map stays unused.
     */
    occupy(candidate: Stuff & Slottable, slot: string): void {
      // Slot-side check: the synthetic spec sets `accepts:
      // 'AdornmentMixin'`, so canOccupy admits only Adornments. Cast
      // to reach the inherited Slotted method — same TypeScript-mixin-
      // constraint reason as in Drivable.resolveControllerSlot.
      const can = (this as unknown as Stuff & Slotted)
        .canOccupy(candidate, slot);
      if (!can) {
        throw new Error(
          `Adornable.occupy: candidate doesn't fit slot '${slot}'`
        );
      }
      this.addFixture(candidate as unknown as Stuff & Adornment, slot);
    }

    vacate(
      slot: string,
      candidate: Stuff & Slottable
    ): (Stuff & Slottable) | null {
      const f = this.fixtureSlots.get(slot);
      if (!f || f !== (candidate as unknown as Stuff & Adornment)) {
        return null;
      }
      this.removeFixture(f);
      return candidate;
    }

    getOccupants(slot: string): ReadonlySet<Stuff & Slottable> {
      const f = this.fixtureSlots.get(slot);
      if (!f) return EMPTY_OCC_SET;
      const set = new Set<Stuff & Slottable>();
      set.add(f as unknown as Stuff & Slottable);
      return set;
    }

    getAllOccupants(): ReadonlyMap<string, ReadonlySet<Stuff & Slottable>> {
      const out = new Map<string, ReadonlySet<Stuff & Slottable>>();
      for (const [k, v] of this.fixtureSlots.entries()) {
        const set = new Set<Stuff & Slottable>();
        set.add(v as unknown as Stuff & Slottable);
        out.set(k, set);
      }
      return out;
    }

    getOccupantCount(slot: string): number {
      return this.fixtureSlots.has(slot) ? 1 : 0;
    }

    isSlotOccupied(slot: string): boolean {
      return this.fixtureSlots.has(slot);
    }

    /**
     * Tear down every fixture before chaining to super. A fixture's
     * own `onDestruct` is responsible for unhooking from any
     * Boundary it's an anchor of — see `BoundaryAnchor`.
     */
    onDestruct(): void {
      const toDestroy = Array.from(this.fixtureSlots.values());
      for (const f of toDestroy) {
        StuffApi.destruct(f as unknown as Stuff);
      }
      this.fixtureSlots.clear();
      super.onDestruct();
    }
  };
}

const EMPTY_OCC_SET: ReadonlySet<Stuff & Slottable> = new Set();

function isLightSourceMarker(f: object): boolean {
  return hasMixinNamed(f, 'LightSourceMixin');
}

function isSmellSourceMarker(f: object): boolean {
  return hasMixinNamed(f, 'SmellSourceMixin');
}

function isSoundSourceMarker(f: object): boolean {
  return hasMixinNamed(f, 'SoundSourceMixin');
}

function hasMixinNamed(f: object, mixinName: string): boolean {
  const ctor = (f as { constructor?: { _mixinName?: string } | undefined })
    .constructor;
  let proto: object | null = ctor as object | null;
  while (proto) {
    const named = (proto as { _mixinName?: string })._mixinName;
    if (named === mixinName) return true;
    proto = Object.getPrototypeOf(proto) as object | null;
  }
  return false;
}
