/**
 * The collection projector — one help topic per authored schema doc.
 *
 * Two halves. The first drives injected fixture docs (no disk, no class
 * resolution) and asserts the SHAPE: the id, the plain-words rendering of
 * both policies, the indexes with their reasons. The second warms from
 * the real `src/schema/` directory and asserts the properties that only
 * the real thing can have — 48 topics, and a field list harvested from
 * the owner class rather than restated in YAML.
 *
 * ⚠ These are unit tests. That `help bank_ledger` reaches a player over a
 * socket is proved by driving, not here — a component test proves
 * rendering, never wiring.
 */

import '../../../test-bootstrap';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import HelpCatalogue, { type AuthorSurface } from '../idea/HelpCatalogue';
import { StuffApi } from '../../api/stuff';
import { makeStuff } from '../../lib/security/__tests__/test-setup';
import { SchemaDoc } from '../../lib/persistence/SchemaDoc';
import { Collections } from '../../lib/persistence/Collections';
import LedgerEntry from '../../lib/banking/LedgerEntry';

const LEDGER = SchemaDoc.parse(
  {
    collection: 'bank_ledger',
    owner: 'LedgerEntry',
    ownerModule: '/lib/banking/LedgerEntry',
    subsystem: 'banking.md',
    summary: 'The money system of record.',
    purpose: 'Every movement of money, append-only.',
    invariants: ['Only BankingApi.postTransaction writes here.'],
    sandbox: 'stamp',
    reset: 'wipe',
    indexes: [
      { keys: { fromAccount: 1 }, why: 'the per-account replay' },
      { keys: { at: -1 }, why: 'time-ordered slices' },
    ],
  },
  'bank_ledger.yaml'
);

const CACHE = SchemaDoc.parse(
  {
    collection: 'renown',
    owner: 'none',
    subsystem: 'renown.md',
    summary: 'A rebuildable standing cache.',
    purpose: 'Derived from renown_events; the log wins.',
    sandbox: { verb: 'shadow', mode: 'skip' },
    reset: { verb: 'keep', because: 'the fixture says so' },
  },
  'renown.yaml'
);

/**
 * A minimal author surface carrying one Api face, so the see-also
 * derivation has something real to point at.
 *
 * ⚠ Injected rather than read from `docs/api/author-surface.json`: that
 * artifact is generated by `pnpm docs` and is not committed, so a test
 * that depended on it would pass or skip depending on whether somebody
 * had run the doc build — which is a test that proves nothing on the day
 * it matters.
 */
const SURFACE: AuthorSurface = {
  consumer: [
    {
      kind: 'api-static',
      module: 'api/banking',
      face: 'BankingApi',
      name: 'postTransaction',
      qualified: 'api/banking#BankingApi.postTransaction',
      signature: 'postTransaction(legs: Leg[]): Promise<void>',
      summary: 'The one writer of the money ledger.',
      signatureTypes: [],
    },
  ],
  extension: [],
  types: [],
};

async function warmed(docs: SchemaDoc[] | null): Promise<HelpCatalogue> {
  const cat = makeStuff(() => new HelpCatalogue());
  await cat.warm({ commandDefs: [], surface: null, schema: docs });
  return cat;
}

describe('the collection projector (injected docs)', () => {
  beforeEach(() => StuffApi.clearAll());
  afterEach(() => {
    vi.restoreAllMocks();
    StuffApi.clearAll();
  });

  it('emits one topic per doc, keyed by collection name', async () => {
    const cat = await warmed([LEDGER, CACHE]);
    const topic = cat.getTopic('collection.bank_ledger');
    expect(topic).not.toBeNull();
    expect(topic!.kind).toBe('collection');
    expect(topic!.title).toBe('bank_ledger');
    expect(topic!.summary).toBe('The money system of record.');
    expect(topic!.source).toEqual({
      subdivision: 'persistence',
      ref: 'bank_ledger',
    });
    // ⚠ How the world remembers things is not a secret.
    expect(topic!.spoiler).toBe(false);
  });

  it('resolves by bare collection name as well as by id', async () => {
    const cat = await warmed([LEDGER, CACHE]);
    expect(cat.findCollectionTopic('bank_ledger')?.id).toBe(
      'collection.bank_ledger'
    );
    expect(cat.findCollectionTopic('collection.bank_ledger')?.id).toBe(
      'collection.bank_ledger'
    );
    expect(cat.findCollectionTopic('nothing')).toBeNull();
  });

  it('lists the collections as their own category', async () => {
    const cat = await warmed([LEDGER, CACHE]);
    const category = cat.categories().find((c) => c.kind === 'collection');
    expect(category).toEqual({
      kind: 'collection',
      title: 'Collections',
      count: 2,
    });
    expect(cat.listByKind('collection').map((e) => e.title)).toEqual([
      'bank_ledger',
      'renown',
    ]);
  });

  it('names the owner, the invariants and every index with its reason', async () => {
    const cat = await warmed([LEDGER]);
    const body = cat.getTopic('collection.bank_ledger')!.body;
    expect(body).toContain('Every movement of money, append-only.');
    expect(body).toContain('Only BankingApi.postTransaction writes here.');
    expect(body).toContain('LedgerEntry');
    expect(body).toContain('fromAccount ascending');
    expect(body).toContain('the per-account replay');
    expect(body).toContain('at descending');
    expect(body).toContain('time-ordered slices');
    expect(body).toContain('docs/subsystems/banking.md');
  });

  it('⭐ renders BOTH policies in plain words, never as a verb literal', async () => {
    const cat = await warmed([LEDGER, CACHE]);
    const ledger = cat.getTopic('collection.bank_ledger')!.body;
    expect(ledger).toContain('STAMPED with the circle');
    expect(ledger).toContain('leaving the circle discards it');
    expect(ledger).toContain('The nightly reset EMPTIES this collection.');
    expect(ledger).not.toContain("{ verb: 'stamp' }");
    expect(ledger).not.toContain("verb: 'wipe'");

    const cache = cat.getTopic('collection.renown')!.body;
    expect(cache).toContain('SKIPPED');
    expect(cache).toContain('derive');
    expect(cache).toContain('KEEPS this collection, because the fixture says so');
  });

  it('says so plainly when no record class owns the collection', async () => {
    const cat = await warmed([CACHE]);
    expect(cat.getTopic('collection.renown')!.body).toContain(
      'goes straight through PersistApi'
    );
  });

  it('says so plainly when a collection has no index', async () => {
    const cat = await warmed([CACHE]);
    expect(cat.getTopic('collection.renown')!.body).toContain(
      'No indexes — nothing queries this by anything but its id.'
    );
  });

  it('⭐ points a collection at the Api face of its owning subsystem', async () => {
    // Derived from `subsystem: banking.md`, never authored — a subsystem
    // doc and its Api face are named for the same concept, which is what
    // makes the edge computable. The owner-class edge beside it is
    // usually dormant: a `Document` subclass is not Stuff and not an Api,
    // so it has no topic of its own to point at.
    const cat = makeStuff(() => new HelpCatalogue());
    await cat.warm({ commandDefs: [], surface: SURFACE, schema: [LEDGER] });
    expect(cat.getTopic('api.BankingApi')).not.toBeNull();
    expect(cat.getTopic('collection.bank_ledger')!.relations).toContainEqual({
      kind: 'see-also',
      targetId: 'api.BankingApi',
      targetTitle: 'BankingApi',
    });
  });

  it('adds no see-also when the subsystem has no Api face', async () => {
    const cat = makeStuff(() => new HelpCatalogue());
    await cat.warm({ commandDefs: [], surface: SURFACE, schema: [CACHE] });
    expect(cat.getTopic('collection.renown')!.relations).toEqual([]);
  });

  it('finds a collection topic through search and typeahead', async () => {
    const cat = await warmed([LEDGER]);
    const groups = cat.search('append-only');
    expect(groups.find((g) => g.kind === 'collection')?.hits[0]?.id).toBe(
      'collection.bank_ledger'
    );
    expect(cat.typeaheadMatch('ledger').map((e) => e.id)).toContain(
      'collection.bank_ledger'
    );
  });

  it('degrades to no collection topics, with one warning, when the docs are unreadable', async () => {
    const warn = vi.spyOn(console, 'warn').mockImplementation(() => {});
    const cat = await warmed(null);
    expect(cat.listByKind('collection')).toEqual([]);
    // Exactly one warning about the schema docs — the one-shot guard.
    // (The fixture also has no author surface, which warns separately.)
    const schemaWarnings = warn.mock.calls.filter((call) =>
      String(call[0]).includes('src/schema/ unreadable')
    );
    expect(schemaWarnings).toHaveLength(1);
    // Command topics are unaffected — the projectors are independent.
    expect(cat.categories().some((c) => c.kind === 'collection')).toBe(false);
  });
});

describe('the collection projector (the real schema directory)', () => {
  beforeEach(() => StuffApi.clearAll());
  afterEach(() => {
    vi.restoreAllMocks();
    StuffApi.clearAll();
  });

  it('reads every shipped doc off disk — one topic per collection', async () => {
    const cat = makeStuff(() => new HelpCatalogue());
    await cat.warm({ commandDefs: [], surface: null });
    const topics = cat.listByKind('collection');
    expect(topics).toHaveLength(Object.values(Collections).length);
    expect(new Set(topics.map((t) => t.title))).toEqual(
      new Set(Object.values(Collections))
    );
  });

  it('⭐ harvests the field list from the OWNER CLASS, not from the YAML', async () => {
    const cat = makeStuff(() => new HelpCatalogue());
    await cat.warm({ commandDefs: [], surface: null });
    const body = cat.getTopic('collection.bank_ledger')!.body;
    expect(body).toContain('Fields (from LedgerEntry):');

    // The assertion that matters: every persistent field the CLASS
    // declares appears in the topic. Add one to LedgerEntry and this
    // topic changes with no edit to bank_ledger.yaml — which is the
    // whole reason the doc does not carry a field list (D3).
    const declared = Object.entries(LedgerEntry.fieldMeta)
      .filter(([, entry]) => entry?.persistent)
      .map(([field]) => field);
    expect(declared.length).toBeGreaterThan(3);
    for (const field of declared) {
      expect(body, `field ${field} missing from the topic`).toContain(
        `  ${field} — `
      );
    }
    // And nothing in the YAML names a field.
    expect(declared.some((f) => f === 'amount' || f === 'at')).toBe(true);
  });
});
