/**
 * AetherMixin — capability for transmitting over the Aether.
 *
 * The Aether is the in-fiction comm-network — the medium that
 * carries non-acoustic communications (tell, future chat channels,
 * future remote emote). Diegetically it can be reflavored per
 * campus zone: a high-tech implant network, a magical resonance
 * field, or both (a hybrid mesh) depending on the setting. The
 * mixin codifies "this Stuff can transmit and receive over the
 * Aether"; the campus-specific narrative is content.
 *
 * Distinct from `VocalMixin` (acoustic transport — say, whisper,
 * shout). A character can be Vocal without being Aetheric (mute
 * implanted, or pre-augmentation), and Aetheric without being
 * Vocal (post-vocal-loss with an implant). Both compose
 * independently onto the host.
 *
 * Verbs gated by this mixin:
 *   - `dm` / `tell` — 1:N private message (1 or more recipients)
 *   - `reply` / `dm .` — pronoun verbs consuming the cohort state
 *   - `broadcast` — one-to-many over the implant network
 *   - `chat` — channel-scoped broadcast
 *
 * DM cohort state lives on this mixin (NOT on Avatar): the last-
 * inbound and last-outbound recipient lists. Runtime-only — never
 * persisted; reset implicitly when the host destructs (logout for
 * Avatars). Read by `reply` / `dm .`; written by `tell` on send.
 * Any Aether-capable being (Avatars with the baseline implant; NPCs
 * with implants when content adds them) participates uniformly.
 *
 * **Composition note for the future emotes slate**: SoulMixin alone
 * grants LOCAL emote (in-room, no network involved). The REMOTE
 * emote (across rooms / zones) requires BOTH SoulMixin AND
 * AetherMixin — the emote performance is generated by the soul,
 * the carrier signal that lifts it across rooms is the Aether.
 * The emotes-slate build should honor this composition gate.
 */

import type { MixinConstructor } from '../mixin';
import type { Stuff } from '../stuff/Stuff';
import { MessageApi } from '../../api/message';
import { Mml } from '../../api/mml';
import type { CommandContributions } from '../../api/command';
import {
  InactiveCapabilityError,
} from '../security/RequiresActive';
import { MixinApi } from '../../api/mixin';

export interface Aether {
  /**
   * Send a private message to one or more targets over the Aether.
   * Single-target produces the classic `tell` rendering ("X → Y: msg"
   * to self, "X → you: msg" to target). Multi-target stamps the full
   * cohort + (optional) `meta.channelId` and adds a "(also to: ...)"
   * cohort hint to per-recipient frames.
   */
  tell(
    target: Stuff | readonly Stuff[],
    text: string,
    opts?: { channelId?: string },
  ): void;

  /**
   * Most-recent cohort of recipients addressed by this Aether host.
   * Read by the `dm .` pronoun verb. `null` until the host has sent.
   */
  getLastOutboundCohort(): readonly Stuff[] | null;

  /**
   * Most-recent cohort that addressed this Aether host. For a 1:1
   * inbound this is `[sender]`; for a multi-party DM it's the full
   * `[sender, ...siblings]` set so a reply-all has every party. Read
   * by `reply`.
   */
  getLastInboundCohort(): readonly Stuff[] | null;

  /**
   * Stamp the host's inbound cohort. Called by the sending Aether on
   * each recipient after `tell` composes the frames. Public on the
   * methods-only contract (an inter-Stuff method) — never invoked
   * externally outside the Aether send path.
   */
  recordInboundCohort(cohort: readonly Stuff[]): void;
}

export function AetherMixin<TBase extends MixinConstructor>(Base: TBase) {
  return class AetherMixin extends Base {
    static _mixinName = 'AetherMixin';

    /**
     * Augment-gated marker: AetherMixin is composed natively on
     * every Avatar (so methods + state exist) but is inert unless
     * an installed augment confers it. The AetherImplant
     * (`/lib/augmentation/AetherImplant`) is the v1 conferrer;
     * `MixinApi.getActiveMixins` reflects implant presence in real
     * time.
     */
    static _augmentGated = true;

    /**
     * Modalities AetherMixin contributes to the sensorium when
     * active. `PerceptionApi.sensorium` walks active mixins and
     * unions their `_grantsModalities`; combined with the BodyPlan
     * organ walk, this is how an implant-bearing Avatar gains the
     * ESP modalities (no native ESP organ in v1).
     */
    static _grantsModalities: readonly string[] = [
      'verbal-esp',
      'emotive-esp',
    ];

    /**
     * Verbs the Aether grants. Tell currently rides here (was
     * temporarily on VocalMixin while the diegetic story was
     * unresolved). Chat and remote-emote will join when their
     * slates ship.
     */
    static commandContributions: CommandContributions = {
      self: ['dm.yaml', 'reply.yaml', 'broadcast.yaml', 'chat.yaml'],
      environment: [],
      inventory: [],
      peers: [],
    };

    /**
     * Cohort state. Runtime-only — NOT in `persistentFields`. Resets
     * implicitly on host destruct (the mixin instance dies with the
     * Stuff). TypeScript `private` per the domain-code rule (the
     * call-security proxy receiver can't reach `#`-private slots from
     * inside mixin methods).
     */
    private _lastInboundDmCohort: Stuff[] | null = null;
    private _lastOutboundDmCohort: Stuff[] | null = null;

    getLastInboundCohort(): readonly Stuff[] | null {
      return this._lastInboundDmCohort;
    }

    getLastOutboundCohort(): readonly Stuff[] | null {
      return this._lastOutboundDmCohort;
    }

    recordInboundCohort(cohort: readonly Stuff[]): void {
      this._lastInboundDmCohort = [...cohort];
    }

    /**
     * Send a private message to `target` (a single Stuff) or
     * `targets` (a readonly Stuff[] — multi-party). Self IS a valid
     * target in the 1:1 case (you can DM yourself).
     *
     * User-supplied text runs through the markdown→MML pipeline so
     * `**bold**`, `*italic*`, `` `@name` ``, and
     * `[label](mudcmd:…)` all work in the body. Mention scope =
     * the speaker's perceivable neighbors (same room) — the
     * Aether-side mention pool (who's on the call) is the chat-
     * slate's concern.
     */
    tell(
      target: Stuff | readonly Stuff[],
      text: string,
      opts?: { channelId?: string },
    ): void {
      // Manual `@RequiresActive('AetherMixin')` — the substrate's
      // augment-gated capability check. TS decorator syntax inside
      // class-factory mixins triggers TS1206, so this guard inlines
      // the same check the decorator would perform. Drop the inline
      // when stage-3 decorators land in tsc + tooling.
      const speaker = this as unknown as Stuff;
      if (!MixinApi.isActive(speaker, 'AetherMixin')) {
        throw new InactiveCapabilityError('AetherMixin', 'tell');
      }

      const targets: readonly Stuff[] = Array.isArray(target)
        ? target
        : [target as Stuff];
      if (targets.length === 0) return;

      const parsed = Mml.markdownToMml(
        text,
        Mml.perceiverMentionResolver(speaker),
      );
      const isMulti = targets.length > 1;
      const channelMeta = opts?.channelId
        ? { channelId: opts.channelId }
        : {};
      const recipientRefs = targets.map((t) => MessageApi.refOf(t));

      // Self-frame body. Single-target: "X → Y: msg". Multi: cohort
      // names spelled out so the sender sees who they hit.
      const selfBody = isMulti
        ? Mml.compose`${Mml.name(speaker)} → ${Mml.fromMarkup(
            targets.map((t) => Mml.name(t).toString()).join(', '),
          )}: ${parsed}`
        : Mml.compose`${Mml.name(speaker)} → ${Mml.name(targets[0]!)}: ${parsed}`;

      MessageApi.scene(speaker)
        .topic('world.speech.dm')
        .modality('verbal-esp')
        .meta(channelMeta)
        .toSelf(selfBody)
        .payload(
          isMulti
            ? {
                speaker: MessageApi.refOf(speaker),
                recipients: recipientRefs,
                text,
              }
            : {
                speaker: MessageApi.refOf(speaker),
                target: MessageApi.refOf(targets[0]!),
                text,
              },
        )
        .send();

      // Per-target frames (one Scene per target — Scene.toTarget caps
      // at one per call; the cohort case needs N).
      for (const t of targets) {
        if (!MixinApi.isSensor(t)) continue;
        let targetBody;
        if (isMulti) {
          const others = targets
            .filter((other) => other !== t)
            .map((other) => Mml.name(other).toString())
            .join(', ');
          const cohortHint = others
            ? Mml.fromMarkup(` (also to: ${others})`)
            : Mml.fromMarkup('');
          targetBody = Mml.compose`${Mml.name(speaker)} → you${cohortHint}: ${parsed}`;
        } else {
          targetBody = Mml.compose`${Mml.name(speaker)} → you: ${parsed}`;
        }
        MessageApi.scene(speaker)
          .topic('world.speech.dm')
          .modality('verbal-esp')
          .meta(channelMeta)
          .toTarget(t, targetBody)
          .payload(
            isMulti
              ? {
                  speaker: MessageApi.refOf(speaker),
                  recipients: recipientRefs,
                  text,
                }
              : {
                  speaker: MessageApi.refOf(speaker),
                  target: MessageApi.refOf(t),
                  text,
                },
          )
          .send();
        // Stamp the recipient's inbound cohort. For 1:1 the cohort is
        // just [speaker]; for multi-party it's [speaker + everyone
        // else on the call] so a reply-all reaches the whole cohort.
        if (MixinApi.isAether(t)) {
          const inbound = isMulti
            ? [speaker, ...targets.filter((o) => o !== t)]
            : [speaker];
          t.recordInboundCohort(inbound);
        }
      }

      this._lastOutboundDmCohort = [...targets];
    }
  };
}
