/**
 * AetherMixin — capability for transmitting over the Aether.
 *
 * The Aether is the in-fiction comm-network — the medium that
 * carries non-acoustic communications (tell, future chat channels,
 * future remote emote). Diegetically it can be reflavored per
 * campus zone: a high-tech implant network, a magical resonance
 * field, or both (a hybrid mesh) depending on the setting. The
 * mixin codifies "this Stuff can transmit and receive over the
 * Aether"; the campus-specific narrative is content.
 *
 * Distinct from `VocalMixin` (acoustic transport — say, whisper,
 * shout). A character can be Vocal without being Aetheric (mute
 * implanted, or pre-augmentation), and Aetheric without being
 * Vocal (post-vocal-loss with an implant). Both compose
 * independently onto the host.
 *
 * Verbs gated by this mixin:
 *   - `tell` — 1:1 (or small ad-hoc group) private message
 *   - future `chat` — channel-scoped broadcast
 *   - future remote emote — composed with `SoulMixin` (see below)
 *
 * **Composition note for the future emotes slate**: SoulMixin alone
 * grants LOCAL emote (in-room, no network involved). The REMOTE
 * emote (across rooms / zones) requires BOTH SoulMixin AND
 * AetherMixin — the emote performance is generated by the soul,
 * the carrier signal that lifts it across rooms is the Aether.
 * The emotes-slate build should honor this composition gate.
 *
 * v1 ships only `tell`. Verb behavior lives on this mixin (the
 * controller is a thin shim that checks `MixinApi.isAether(speaker)`
 * and delegates to `aether.tell(target, text)`).
 */

import type { MixinConstructor } from '../mixin';
import type { Stuff } from '../stuff/Stuff';
import { MessageApi } from '../../api/message';
import { Mml } from '../../api/mml';
import type { CommandContributions } from '../../api/command';

export interface Aether {
  tell(target: Stuff, text: string): void;
}

export function AetherMixin<TBase extends MixinConstructor>(Base: TBase) {
  return class AetherMixin extends Base {
    static _mixinName = 'AetherMixin';

    /**
     * Verbs the Aether grants. Tell currently rides here (was
     * temporarily on VocalMixin while the diegetic story was
     * unresolved). Chat and remote-emote will join when their
     * slates ship.
     */
    static commandContributions: CommandContributions = {
      self: ['tell.yaml'],
      environment: [],
      inventory: [],
      peers: [],
    };

    /**
     * Send a private message to `target` over the Aether. Chat-form
     * rendering: `<speaker> → <target>: <body>` from the sender's
     * view; `<speaker> → you: <body>` from the recipient's. Self IS
     * a valid target (you can DM yourself — note-to-self is a real
     * use case).
     *
     * User-supplied text runs through the markdown→MML pipeline so
     * `**bold**`, `*italic*`, `` `code` ``, `@name`, and
     * `[label](mudcmd:…)` all work in the body. Mention scope =
     * the speaker's perceivable neighbors (same room) — the
     * Aether-side mention pool (who's on the call) is the chat-
     * slate's concern.
     */
    tell(target: Stuff, text: string): void {
      const speaker = this as unknown as Stuff;
      const parsed = Mml.markdownToMml(
        text,
        Mml.perceiverMentionResolver(speaker),
      );
      MessageApi.scene(speaker)
        .topic('world.speech.tell')
        .toSelf(
          Mml.compose`${Mml.name(speaker)} → ${Mml.name(target)}: ${parsed}`,
        )
        .toTarget(
          target,
          Mml.compose`${Mml.name(speaker)} → you: ${parsed}`,
        )
        .payload({
          speaker: MessageApi.refOf(speaker),
          target: MessageApi.refOf(target),
          text,
        })
        .send();
    }
  };
}
