/**
 * AetherMixin — capability for transmitting over the Aether.
 *
 * The Aether is the in-fiction comm-network — the medium that
 * carries non-acoustic communications (tell, future chat channels,
 * future remote emote). Diegetically it can be reflavored per
 * campus zone: a high-tech implant network, a magical resonance
 * field, or both (a hybrid mesh) depending on the setting. The
 * mixin codifies "this Stuff can transmit and receive over the
 * Aether"; the campus-specific narrative is content.
 *
 * Distinct from `VocalMixin` (acoustic transport — say, whisper,
 * shout). A character can be Vocal without being Aetheric (mute
 * implanted, or pre-augmentation), and Aetheric without being
 * Vocal (post-vocal-loss with an implant). Both compose
 * independently onto the host.
 *
 * Verbs gated by this mixin:
 *   - `tell` — 1:1 (or small ad-hoc group) private message
 *   - future `chat` — channel-scoped broadcast
 *   - future remote emote — composed with `SoulMixin` (see below)
 *
 * **Composition note for the future emotes slate**: SoulMixin alone
 * grants LOCAL emote (in-room, no network involved). The REMOTE
 * emote (across rooms / zones) requires BOTH SoulMixin AND
 * AetherMixin — the emote performance is generated by the soul,
 * the carrier signal that lifts it across rooms is the Aether.
 * The emotes-slate build should honor this composition gate.
 *
 * v1 ships only `tell`. Verb behavior lives on this mixin (the
 * controller is a thin shim that checks `MixinApi.isAether(speaker)`
 * and delegates to `aether.tell(target, text)`).
 */

import type { MixinConstructor } from '../mixin';
import type { Stuff } from '../stuff/Stuff';
import { MessageApi } from '../../api/message';
import { Mml } from '../../api/mml';
import type { CommandContributions } from '../../api/command';
import {
  InactiveCapabilityError,
} from '../security/RequiresActive';
import { MixinApi } from '../../api/mixin';
import { recordInboundCohort } from '../social/dm-cohort';

export interface Aether {
  tell(target: Stuff, text: string): void;
  /**
   * Multi-target send. Each recipient gets a frame stamped with the
   * full cohort + optional `meta.channelId` (when the cohort is
   * backed by an ad-hoc channel). The body carries "(also to: ...)"
   * for the cohort hint.
   */
  tellMany(
    targets: readonly Stuff[],
    text: string,
    opts?: { channelId?: string },
  ): void;
}

export function AetherMixin<TBase extends MixinConstructor>(Base: TBase) {
  return class AetherMixin extends Base {
    static _mixinName = 'AetherMixin';

    /**
     * Augment-gated marker: AetherMixin is composed natively on
     * every Avatar (so methods + state exist) but is inert unless
     * an installed augment confers it. The AetherImplant
     * (`/lib/augmentation/AetherImplant`) is the v1 conferrer;
     * `MixinApi.getActiveMixins` reflects implant presence in real
     * time.
     */
    static _augmentGated = true;

    /**
     * Modalities AetherMixin contributes to the sensorium when
     * active. `PerceptionApi.sensorium` walks active mixins and
     * unions their `_grantsModalities`; combined with the BodyPlan
     * organ walk, this is how an implant-bearing Avatar gains the
     * ESP modalities (no native ESP organ in v1).
     */
    static _grantsModalities: readonly string[] = [
      'verbal-esp',
      'emotive-esp',
    ];

    /**
     * Verbs the Aether grants. Tell currently rides here (was
     * temporarily on VocalMixin while the diegetic story was
     * unresolved). Chat and remote-emote will join when their
     * slates ship.
     */
    static commandContributions: CommandContributions = {
      self: ['dm.yaml', 'reply.yaml', 'broadcast.yaml', 'chat.yaml'],
      environment: [],
      inventory: [],
      peers: [],
    };

    /**
     * Send a private message to `target` over the Aether. Chat-form
     * rendering: `<speaker> → <target>: <body>` from the sender's
     * view; `<speaker> → you: <body>` from the recipient's. Self IS
     * a valid target (you can DM yourself — note-to-self is a real
     * use case).
     *
     * User-supplied text runs through the markdown→MML pipeline so
     * `**bold**`, `*italic*`, `` `code` ``, `@name`, and
     * `[label](mudcmd:…)` all work in the body. Mention scope =
     * the speaker's perceivable neighbors (same room) — the
     * Aether-side mention pool (who's on the call) is the chat-
     * slate's concern.
     */
    tell(target: Stuff, text: string): void {
      // Manual `@RequiresActive('AetherMixin')` — the substrate's
      // augment-gated capability check. TS decorator syntax inside
      // class-factory mixins triggers TS1206, so this guard inlines
      // the same check the decorator would perform. Drop the inline
      // when stage-3 decorators land in tsc + tooling.
      const speaker = this as unknown as Stuff;
      if (!MixinApi.isActive(speaker, 'AetherMixin')) {
        throw new InactiveCapabilityError('AetherMixin', 'tell');
      }
      const parsed = Mml.markdownToMml(
        text,
        Mml.perceiverMentionResolver(speaker),
      );
      MessageApi.scene(speaker)
        .topic('world.speech.dm')
        .modality('verbal-esp')
        .toSelf(
          Mml.compose`${Mml.name(speaker)} → ${Mml.name(target)}: ${parsed}`,
        )
        .toTarget(
          target,
          Mml.compose`${Mml.name(speaker)} → you: ${parsed}`,
        )
        .payload({
          speaker: MessageApi.refOf(speaker),
          target: MessageApi.refOf(target),
          text,
        })
        .send();
      stampInboundCohort(target, [speaker]);
    }

    tellMany(
      targets: readonly Stuff[],
      text: string,
      opts?: { channelId?: string },
    ): void {
      const speaker = this as unknown as Stuff;
      if (!MixinApi.isActive(speaker, 'AetherMixin')) {
        throw new InactiveCapabilityError('AetherMixin', 'tellMany');
      }
      if (targets.length === 0) return;
      if (targets.length === 1) {
        // Degenerate case — single recipient, same as `tell`.
        this.tell(targets[0]!, text);
        return;
      }
      const parsed = Mml.markdownToMml(
        text,
        Mml.perceiverMentionResolver(speaker),
      );

      const recipientRefs = targets.map((t) => MessageApi.refOf(t));
      const recipientNames = targets
        .map((t) => Mml.name(t).toString())
        .join(', ');

      // Self frame — cohort list spelled out.
      MessageApi.scene(speaker)
        .topic('world.speech.dm')
        .modality('verbal-esp')
        .meta(opts?.channelId ? { channelId: opts.channelId } : {})
        .toSelf(
          Mml.compose`${Mml.name(speaker)} → ${Mml.fromMarkup(recipientNames)}: ${parsed}`,
        )
        .payload({
          speaker: MessageApi.refOf(speaker),
          recipients: recipientRefs,
          text,
        })
        .send();

      // Per-target frame — "you" + cohort hint for the others.
      for (const t of targets) {
        if (!MixinApi.isSensor(t)) continue;
        const others = targets
          .filter((other) => other !== t)
          .map((other) => Mml.name(other).toString())
          .join(', ');
        const cohortHint = others
          ? Mml.fromMarkup(` (also to: ${others})`)
          : Mml.fromMarkup('');
        MessageApi.scene(speaker)
          .topic('world.speech.dm')
          .modality('verbal-esp')
          .meta(opts?.channelId ? { channelId: opts.channelId } : {})
          .toTarget(
            t,
            Mml.compose`${Mml.name(speaker)} → you${cohortHint}: ${parsed}`,
          )
          .payload({
            speaker: MessageApi.refOf(speaker),
            recipients: recipientRefs,
            text,
          })
          .send();
        // Recipient's inbound cohort = sender + the other recipients.
        const inbound = [speaker, ...targets.filter((o) => o !== t)];
        stampInboundCohort(t, inbound);
      }
    }
  };
}

/**
 * Helper — stamp the recipient's last-inbound cohort when the
 * recipient is an Avatar. Lazy-loaded `Avatar` class to dodge the
 * `Avatar → AetherMixin → Aether.ts` cycle at module init.
 */
function stampInboundCohort(recipient: Stuff, cohort: readonly Stuff[]): void {
  // Importing `Avatar` eagerly would create a cycle (Avatar composes
  // AetherMixin). Use a structural sniff instead: an `Avatar` carries
  // `getPlayerId()`. Anything else (NPCs, login pseudo-stuff) skips.
  const av = recipient as Stuff & { getPlayerId?: () => string };
  if (typeof av.getPlayerId !== 'function') return;
  recordInboundCohort(av as unknown as Parameters<typeof recordInboundCohort>[0], cohort);
}
