/*
**  Monster : statue
**  Creator : Torenthal
**
**  Generated By Monster Generator (version 2.1)
*/

inherit MonsterCode;


void extra_create()
{
    set_name("anestimos");
    add_alias("statue");
    add_alias("perfect statue");
    set_short("Anestimos the statue sits on top of a black marble stand");
    set_long("Anestimos is an example of perfection.  Perfectly carven in living stone,\n" +
        "he stands and waits to grant travellers their just due, helping to magically\n" +
        "increase their statistics.  Facing him, he communicates to you in some strange\n" +
        "fashion that if you type 'raise <stat>' then he will attempt to help you.\n" +
        "He also communicates that 'cost <stat>' will tell how much it will cost you\n"+
        "to increase that stat by one, and 'cost all' will show you how much "
       +"it will\ncost you to raise each of your stats by one.\n");
    set_race("human");
    (int)PROP->add_property(THISO, "no summon");
    set_max_hp(10000);
    set_max_fatigue(100000);
    set_max_damage(25);
    set_hit_bonus(3);
    set_damage_bonus(3);
    set_type("edged");
    set_natural_ac(25);
    set_offensive_level(300);
    set_defensive_level(300);
    set_alignment("angelic");
    set_aggressive(0);
    set_heal_rate(100);
    set_heal_amount(100);
    set_stat("str", 100);
    set_stat("int", 100);
    set_stat("dex", 100);
    set_stat("con", 100);
    set_stat("chr", 100);
    set_stat("wil", 100);
}
